# Generated by Django 5.1.4 on 2025-01-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('forms_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GosStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScraVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('team_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldBuilderAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(verbose_name='Time In')),
                ('time_out', models.DateTimeField(null=True, verbose_name='Time Out')),
                ('field_builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.fieldbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='GosAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(verbose_name='Time In')),
                ('time_out', models.DateTimeField(null=True, verbose_name='Time Out')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.gosstudent')),
            ],
        ),
        migrations.CreateModel(
            name='ScraVisitorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(verbose_name='Time In')),
                ('time_out', models.DateTimeField(null=True, verbose_name='Time Out')),
                ('scra_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.scravisitor')),
            ],
        ),
    ]
