# Generated by Django 5.1.6 on 2025-02-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gosstudent",
            name="gos_program",
            field=models.CharField(
                choices=[("UNASSIGNED", "Unassigned"), ("FRC", "Frc"), ("FTC", "Ftc")],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gosstudent",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (0, "Unassigned"),
                    (13, "Mentor"),
                    (12, "Senior"),
                    (11, "Junior"),
                    (10, "Sophomore"),
                    (9, "Freshman"),
                    (8, "Eighth"),
                    (7, "Seventh"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="gosstudent",
            name="preseason_crew",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("Crew 1", "Crew1"),
                    ("Crew 2", "Crew2"),
                    ("Crew 3", "Crew3"),
                    ("Crew 4", "Crew4"),
                    ("Crew 5", "Crew5"),
                    ("Crew 6", "Crew6"),
                    ("Crew 7", "Crew7"),
                    ("Crew 8", "Crew8"),
                    ("IP Data Science", "Independentprojectdatascience"),
                    ("IP Meep Meep", "Independentprojectmeepmeep"),
                    ("IP Curriculum", "Independentcurriculum"),
                    ("Floating Mentor", "Floatingmentor"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gosstudent",
            name="subteam",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("Design", "Design"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Software", "Software"),
                    ("Data Science", "Datascience"),
                    ("FTC Hypatia", "Ftchypatia"),
                    ("FTC Hopper", "Ftchopper"),
                    ("FTC Lovelace", "Ftclovelace"),
                    ("FTC Juniors", "Ftcjuniors"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
    ]
