# Generated by Django 5.1.6 on 2025-08-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_gosstudent_gos_program_gosstudent_grade_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FieldBuilder",
            new_name="FieldBuilder2025",
        ),
        migrations.RenameModel(
            old_name="FieldBuilderAttendance",
            new_name="FieldBuilderAttendance2025",
        ),
        migrations.RenameModel(
            old_name="GosAttendance",
            new_name="GosAttendance2025",
        ),
        migrations.RenameModel(
            old_name="GosStudent",
            new_name="GosStudent2025",
        ),
        migrations.RenameModel(
            old_name="ScraVisitor",
            new_name="ScraVisitor2025",
        ),
        migrations.RenameModel(
            old_name="ScraVisitorAttendance",
            new_name="ScraVisitorAttendance2025",
        ),
    ]
