# Generated by Django 5.1.6 on 2025-08-24 23:13

import attendance.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_rename_fieldbuilder_fieldbuilder2025_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldBuilder2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("forms_completed", models.BooleanField(default=False)),
            ],
            bases=(models.Model, attendance.models.mixins.InOutTimeMixin),
        ),
        migrations.CreateModel(
            name="GosStudent2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfid", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gos_program",
                    models.CharField(
                        choices=[("UNASSIGNED", "Unassigned")],
                        default="UNASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "preseason_crew",
                    models.CharField(
                        choices=[("UNASSIGNED", "Unassigned")],
                        default="UNASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "subteam",
                    models.CharField(
                        choices=[("UNASSIGNED", "Unassigned")],
                        default="UNASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (12, "Senior"),
                            (11, "Junior"),
                            (10, "Sophomore"),
                            (9, "Freshman"),
                            (8, "Eighth"),
                            (7, "Seventh"),
                        ]
                    ),
                ),
            ],
            bases=(models.Model, attendance.models.mixins.InOutTimeMixin),
        ),
        migrations.CreateModel(
            name="ScraVisitor2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("team_number", models.IntegerField()),
            ],
            bases=(models.Model, attendance.models.mixins.InOutTimeMixin),
        ),
        migrations.CreateModel(
            name="FieldBuilderAttendance2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_in", models.DateTimeField(verbose_name="Time In")),
                ("time_out", models.DateTimeField(null=True, verbose_name="Time Out")),
                (
                    "field_builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.fieldbuilder2026",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GosAttendance2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_in", models.DateTimeField(verbose_name="Time In")),
                ("time_out", models.DateTimeField(null=True, verbose_name="Time Out")),
                ("purpose", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.gosstudent2026",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScraVisitorAttendance2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_in", models.DateTimeField(verbose_name="Time In")),
                ("time_out", models.DateTimeField(null=True, verbose_name="Time Out")),
                ("purpose", models.CharField(max_length=100)),
                (
                    "scra_visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.scravisitor2026",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
