# Generated by Django 5.1.6 on 2025-08-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_fieldbuilder2026_gosstudent2026_scravisitor2026_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gosstudent2026",
            name="rfid",
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
