# Generated by Django 5.1.6 on 2025-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_gosstudent2026_rfid"),
    ]

    operations = [
        migrations.AddField(
            model_name="gosstudent2026",
            name="business_subteam",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("Media", "Media"),
                    ("Awards", "Awards"),
                    ("Finance", "Finance"),
                    ("Outreach", "Outreach"),
                    ("FIRST Ladies", "First Ladies"),
                    ("Advocacy", "Advocacy"),
                ],
                default="UNASSIGNED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="gosstudent2026",
            name="preseason_crew",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("Crew 1", "Crew1"),
                    ("Crew 2", "Crew2"),
                    ("Crew 3", "Crew3"),
                    ("Crew 4", "Crew4"),
                    ("Crew 5", "Crew5"),
                    ("Crew 6", "Crew6"),
                    ("IP Data Science", "Ip Data Science"),
                    ("IP Carbon Footprint", "Ip Carbon Footprint"),
                    ("IP Advocacy", "Ip Advocacy"),
                    ("IP Automated Graphics", "Ip Automated Graphics"),
                    ("IP Elementary Robotics", "Ip Elementary Robotics"),
                ],
                default="UNASSIGNED",
                max_length=30,
            ),
        ),
    ]
