# Generated by Django 5.1.6 on 2025-09-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_gosstudent2026_business_subteam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gosstudent2026",
            name="preseason_crew",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("Tech Lead", "Tech Lead"),
                    ("Crew 1", "Crew1"),
                    ("Crew 2", "Crew2"),
                    ("Crew 3", "Crew3"),
                    ("Crew 4", "Crew4"),
                    ("Crew 5", "Crew5"),
                    ("Crew 6", "Crew6"),
                    ("IP Data Science", "Ip Data Science"),
                    ("IP Carbon Footprint", "Ip Carbon Footprint"),
                    ("IP Advocacy", "Ip Advocacy"),
                    ("IP Automated Graphics", "Ip Automated Graphics"),
                    ("IP Elementary Robotics", "Ip Elementary Robotics"),
                ],
                default="UNASSIGNED",
                max_length=30,
            ),
        ),
    ]
