# Generated by Django 5.1.6 on 2025-09-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_alter_gosstudent2026_business_subteam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gosstudent2026",
            name="gos_program",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("FRC", "Frc"),
                    ("FTC", "Ftc"),
                    ("Mentor", "Mentor"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gosstudent2026",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (12, "Senior"),
                    (11, "Junior"),
                    (10, "Sophomore"),
                    (9, "Freshman"),
                    (8, "Eighth"),
                    (7, "Seventh"),
                    (0, "Mentor"),
                ]
            ),
        ),
    ]
