# Generated by Django 5.1.6 on 2025-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_gosstudent2026_gos_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gosstudent2025",
            name="inactive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gosstudent2026",
            name="inactive",
            field=models.BooleanField(default=False),
        ),
    ]
