# Generated by Django 5.1.6 on 2026-02-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_add_inactive_to_gosstudents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gosstudent2026",
            name="subteam",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("Design", "Design"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Software", "Software"),
                    ("Data Science", "Datascience"),
                    ("FTC Hypatia", "Ftchypatia"),
                    ("FTC Hopper", "Ftchopper"),
                    ("FTC Lovelace", "Ftclovelace"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
    ]
