name: Test

on: [pull_request, push]

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install Deps
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: coverage run ./manage.py test

      - name: Display Coverage Report
        run: coverage report